---
#dependency:
#  name: galaxy
driver:
  name: docker
platforms:
  - name: rhythmic-amzn2
    image: amazonlinux:latest
    pre_build_image: true
provisioner:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
